name: Validate Translations

on:
  pull_request:
    types: [opened, synchronize, labeled]
    # Run when PR is opened, updated, or labeled
  # Only run if PR has 'translation' label

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    # Only run if the PR has the 'translation' label
    if: contains(github.event.pull_request.labels.*.name, 'translation')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Validate translation completeness
      run: |
        python .github/scripts/validate_translations.py
