name: Validate Translations

on:
  push:
    paths:
      - 'custom_components/tududi_integration/strings.json'
      - 'custom_components/tududi_integration/translations/*.json'
  pull_request:
    types: [opened, synchronize, labeled]
    # Run when PR is opened, updated, or labeled

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    # For PRs: only run if the PR has the 'translation' label
    # For pushes: run automatically (already filtered by paths)
    if: |
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'translation')) ||
      (github.event_name == 'push')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Validate translation completeness
      run: |
        python .github/scripts/validate_translations.py
